#!/usr/bin/env bash

ROOT=/home/gstupp/projects/create_compil
#ROOT=~/create_compil
DOWNLOAD_ROOT=$ROOT/data

UNIPROT_DATA=$DOWNLOAD_ROOT/uniprot
METAHIT_DATA=$DOWNLOAD_ROOT/metahit
REFSEQ_DATA=$DOWNLOAD_ROOT/refseq
HMGI_DATA=$DOWNLOAD_ROOT/hmgi
CRAPOME_DATA=$DOWNLOAD_ROOT/crapome
MGM_DATA=$DOWNLOAD_ROOT/mgm
FOOD_DATA=$DOWNLOAD_ROOT/food

PROCESSED_DATA=$ROOT/processed