#!/usr/bin/env bash

ROOT=/home/gstupp/projects/create_compil
#ROOT=~/create_compil
DOWNLOAD_ROOT=$ROOT/data

UNIPROT_DATA=$DOWNLOAD_ROOT/uniprot
METAHIT_DATA=$DOWNLOAD_ROOT/metahit
REFSEQ_DATA=$DOWNLOAD_ROOT/refseq
HMGI_DATA=$DOWNLOAD_ROOT/hmgi
CRAPOME_DATA=$DOWNLOAD_ROOT/crapome
MGM_DATA=$DOWNLOAD_ROOT/mgm
FOOD_DATA=$DOWNLOAD_ROOT/food
IGC_DATA=$DOWNLOAD_ROOT/igc
HMP2_DATA=$DOWNLOAD_ROOT/hmp2/v2

PROCESSED_DATA=$ROOT/processed

mkdir -p $DOWNLOAD_ROOT
mkdir -p $PROCESSED_DATA